- key:               vgc-testnet
  name:              Fiveg Testnet
  client:            fiveg                                # API client name.
  server:            http://user:password@127.0.0.1:8345  # Public Fiveg node endpoint.
  height:            2000                                 # Initial block number from which sync will be started.
  min_confirmations: 6                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         http://fiveg.cash/address/#{address}
    transaction:     http://fiveg.cash/tx/#{txid}
  status:            active
